nelmio_cors:
    defaults:
        origin_regex: false
        allow_origin: ['http://localhost:3000']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS', 'PATCH']
        allow_headers: ['Content-Type', 'Authorization', 'X-AUTH-TOKEN']
        expose_headers: ['Content-Length', 'X-Total-Count']
        max_age: 3600
        allow_credentials: true
    paths:
        '^/api/':
            allow_origin: ['http://localhost:3000']
            allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS', 'PATCH']
            allow_headers: ['Content-Type', 'Authorization', 'X-AUTH-TOKEN']
            allow_credentials: true
            max_age: 3600
