vich_uploader:
    db_driver: orm

    mappings:
        travelbook_covers:
            uri_prefix: /uploads/images/travelbooks
            upload_destination: '%kernel.project_dir%/public/uploads/images/travelbooks'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_remove: true
            delete_on_update: true

        travelbook_photos:
            uri_prefix: /uploads/photos
            upload_destination: '%kernel.project_dir%/public/uploads/photos'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_remove: true
            delete_on_update: true
