# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

parameters:
    uploads_directory: '%kernel.project_dir%/public/uploads'

services:
    # Default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: true        # Permet d'assurer que les services sont accessibles (optionnel)

    # Enregistre le CORS Listener
    App\EventListener\CorsListener:
        autowire: true
        autoconfigure: true
        tags:
            - { name: kernel.event_listener, event: kernel.response }

    # Charge automatiquement tous les services de `src/`
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'


        # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
